In [1]:
import pandas as pd
pd.set_option('max_columns', 0)
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

import warnings
warnings.filterwarnings('ignore')

import functions as fun
import csv
import pickle

In [2]:
%load_ext autoreload
%autoreload

In [3]:
%reload_ext autoreload

In [4]:
df = pd.read_csv('diabetic_data.csv')
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [5]:
df.shape

(101766, 50)

In [6]:
df.weight.unique()

array(['?', '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [7]:
fun.missing_data(df)

Empty DataFrame
Columns: [Total, Percent]
Index: []

no missing data - all null values have values other than nan

In [8]:
df.replace(to_replace='?', value='unknown', inplace=True)
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [8]:
df.A1Cresult.value_counts()

None    84748
>8       8216
Norm     4990
>7       3812
Name: A1Cresult, dtype: int64

In [9]:
diag_codes = {}
for num in range(390, 460):
    diag_codes[num] = 'circulatory'
    for num in range(460, 520):
        diag_codes[num] = 'respiratory'
        for num in range(520, 580):
            diag_codes[num] = 'digestive'
            for num in range(800, 1000):
                diag_codes[num] = 'injury'
                for num in range(710, 740):
                    diag_codes[num] = 'musculoskeletal'
                    for num in range(580, 630):
                        diag_codes[num] = 'genitourinary'
                        for num in range(140, 240):
                            diag_codes[num] = 'neoplasms'

KeyboardInterrupt:

In [11]:
diag_codes[239]

'neoplasms'

In [13]:
tester = {785:'circulatory', 786:'respiratory', 787:'digestive',
           788:'genitourinary', 250.00:'diabetes'}
diag_codes.update(tester)

In [17]:
diag_codes[240]

'other'

In [16]:
temp = {}
for num in range(0, 800):
    if num not in diag_codes:
        temp[num] = 'other'
        diag_codes.update(temp)

In [22]:
# w = csv.writer(open("diag_codes.csv", "w"))
# for key, val in diag_codes.items():
#     w.writerow([key, val])

In [24]:
f = open("diag_codes.pkl","wb")
pickle.dump(diag_codes,f)
f.close()

In [26]:
df_ids = pd.read_csv('IDs_mapping.csv')
# df_ids.tail(30)

In [27]:
ad = df_ids.iloc[:8,:].set_index('admission_type_id')
df_split1 = df_ids.iloc[9:, :]
# ad

In [28]:
df_split2 = df_ids.iloc[33:, :]
dis = df_split1.iloc[1:32,:].set_index('admission_type_id')
# dis.head()

In [29]:
source = df_split2.iloc[9:,:].set_index('admission_type_id')
# source

In [30]:
admission_dict = {}
for i in range(len(ad)):
    id_descript = ad.iloc[i]['description']
    admission_dict[i+1] = id_descript

In [31]:
admission_dict[4]

'Newborn'

In [32]:
discharge_dict = {}
for i in range(len(dis)):
    id_descript = dis.iloc[i]['description']
    discharge_dict[i+1] = id_descript

In [33]:
discharge_dict[5]

'Discharged/transferred to another type of inpatient care institution'

In [34]:
ad_source_dict = {}
for i in range(len(source)):
    id_descript = source.iloc[i]['description']
    ad_source_dict[i+1] = id_descript

In [35]:
ad_source_dict[6]

' Transfer from another health care facility'

In [36]:
# w = csv.writer(open("admission_dict.csv", "w"))
# for key, val in admission_dict.items():
#     w.writerow([key, val])

In [37]:
# w = csv.writer(open("discharge_dict.csv", "w"))
# for key, val in discharge_dict.items():
#     w.writerow([key, val])

In [38]:
# w = csv.writer(open("ad_source_dict.csv", "w"))
# for key, val in ad_source_dict.items():
#     w.writerow([key, val])

In [39]:
f = open("admission_dict.pkl","wb")
pickle.dump(admission_dict,f)
f.close()

In [40]:
f = open("discharge_dict.pkl","wb")
pickle.dump(discharge_dict,f)
f.close()

In [41]:
f = open("ad_source_dict.pkl","wb")
pickle.dump(ad_source_dict,f)
f.close()

In [42]:
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [43]:
df.to_csv('next_diabetes.csv', index=False)

In [9]:
discharge_disposition = {1:{1:'home', 21:'law enforcement', 30:'still patient',
           81:'home after acute care', 87:'law enforcement after acute care'}, 
            2:{ 2:'short-term hospital', 5:'cancer center/childrens hospital', 
               9:'invalid', 43:'federal facility', 66:'critical access hospital', 
              82:'short-term after acute care'}}

In [10]:
discharge_disposition[1][21]

'law enforcement'

In [11]:
f = open("discharge_disposition.pkl","wb")
pickle.dump(discharge_disposition,f)
f.close()